name: Fetch Data

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Fetch Strava data
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          TRAKT_ACCESS_TOKEN: ${{ secrets.TRAKT_ACCESS_TOKEN }}
          FANART_API_KEY: ${{ secrets.FANART_API_KEY }}
        run: go run cmd/fetch-data/fetch_data.go

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes detected, nothing to commit."
            exit 0
          fi
          git commit -m "Update Strava data"
          git push origin main

